# Generated by Django 5.0.6 on 2024-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Unresolved'), (1, 'Resolved')], default=0)),
                ('details', models.TextField(max_length=5000)),
                ('resources', models.TextField(max_length=5000)),
                ('tasks', models.TextField(max_length=5000)),
                ('updates', models.TextField(max_length=5000)),
            ],
        ),
    ]
