# Generated by Django 5.0.6 on 2024-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_disaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=1000)),
                ('allocation_status', models.IntegerField(choices=[(0, 'Not Allocated'), (1, 'Allocated')], default=0)),
                ('details', models.TextField(max_length=5000)),
                ('quantity', models.IntegerField()),
                ('allocation_history', models.TextField(max_length=5000)),
                ('assignment', models.TextField(max_length=5000)),
            ],
        ),
        migrations.RenameField(
            model_name='disaster',
            old_name='resources',
            new_name='resources_needed',
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Incompleted'), (1, 'Completed')], default=0)),
                ('description', models.TextField(max_length=5000)),
                ('updates', models.TextField(max_length=5000)),
                ('assigned_resources', models.ManyToManyField(to='app.resources')),
            ],
        ),
    ]
