# Generated by Django 5.0.6 on 2024-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_resources_rename_resources_disaster_resources_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='resources',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
